package pojos;
// Generated 14-ene-2015 14:44:58 by Hibernate Tools 3.6.0



/**
 * DatosTienda generated by hbm2java
 */
public class DatosTienda  implements java.io.Serializable {


     private int idtienda;
     private String nif;
     private String nombre;
     private String calle;
     private String telefono;
     private String fax;

    public DatosTienda() {
    }

	
    public DatosTienda(int idtienda) {
        this.idtienda = idtienda;
    }
    public DatosTienda(int idtienda, String nif, String nombre, String calle, String telefono, String fax) {
       this.idtienda = idtienda;
       this.nif = nif;
       this.nombre = nombre;
       this.calle = calle;
       this.telefono = telefono;
       this.fax = fax;
    }
   
    public int getIdtienda() {
        return this.idtienda;
    }
    
    public void setIdtienda(int idtienda) {
        this.idtienda = idtienda;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


