package pojos;
// Generated 14-ene-2015 14:44:58 by Hibernate Tools 3.6.0



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idempleado;
     private Integer idtienda;
     private String nombre;
     private String ape1;
     private String ape2;
     private String dni;
     private String telefono;
     private String movil;
     private String domicilio;

    public Empleado() {
    }

	
    public Empleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public Empleado(int idempleado, Integer idtienda, String nombre, String ape1, String ape2, String dni, String telefono, String movil, String domicilio) {
       this.idempleado = idempleado;
       this.idtienda = idtienda;
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.dni = dni;
       this.telefono = telefono;
       this.movil = movil;
       this.domicilio = domicilio;
    }
   
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public Integer getIdtienda() {
        return this.idtienda;
    }
    
    public void setIdtienda(Integer idtienda) {
        this.idtienda = idtienda;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMovil() {
        return this.movil;
    }
    
    public void setMovil(String movil) {
        this.movil = movil;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }




}


