package pojos;
// Generated 14-ene-2015 14:44:58 by Hibernate Tools 3.6.0



/**
 * Facprod generated by hbm2java
 */
public class Facprod  implements java.io.Serializable {


     private Integer idfacprod;
     private Producto producto;
     private Factura factura;
     private Integer cantidad;
     private Float importe;

    public Facprod() {
    }

	
    public Facprod(Producto producto, Factura factura) {
        this.producto = producto;
        this.factura = factura;
    }
    public Facprod(Producto producto, Factura factura, Integer cantidad, Float importe) {
       this.producto = producto;
       this.factura = factura;
       this.cantidad = cantidad;
       this.importe = importe;
    }
   
    public Integer getIdfacprod() {
        return this.idfacprod;
    }
    
    public void setIdfacprod(Integer idfacprod) {
        this.idfacprod = idfacprod;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }




}


