package pojos;
// Generated 14-ene-2015 14:44:58 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private String dniCliente;
     private Date fecha;
     private String atendido;
     private Float importe;
     private Set facprods = new HashSet(0);

    public Factura() {
    }

	
    public Factura(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Factura(String dniCliente, Date fecha, String atendido, Float importe, Set facprods) {
       this.dniCliente = dniCliente;
       this.fecha = fecha;
       this.atendido = atendido;
       this.importe = importe;
       this.facprods = facprods;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAtendido() {
        return this.atendido;
    }
    
    public void setAtendido(String atendido) {
        this.atendido = atendido;
    }
    public Float getImporte() {
        return this.importe;
    }
    
    public void setImporte(Float importe) {
        this.importe = importe;
    }
    public Set getFacprods() {
        return this.facprods;
    }
    
    public void setFacprods(Set facprods) {
        this.facprods = facprods;
    }




}


