package pojos;
// Generated 14-ene-2015 14:44:58 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private Integer stock;
     private Float precio;
     private Set facprods = new HashSet(0);

    public Producto() {
    }

    public Producto(String nombre, Integer stock, Float precio, Set facprods) {
       this.nombre = nombre;
       this.stock = stock;
       this.precio = precio;
       this.facprods = facprods;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Set getFacprods() {
        return this.facprods;
    }
    
    public void setFacprods(Set facprods) {
        this.facprods = facprods;
    }




}


